---
title: Haciendo una aplicación en Rails - Parte 4
layout: post
read_time: 5 min.
locale: es
---

Algo que le faltaba a nuestra aplicacion eran validaciones, y las agregaremos con desarrollo guiado por pruebas.

Para ver las otras partes de esta serie de posts podes usar la siguiente guia:
- [Haciendo una aplicación en Rails](/2020/03/28/stock-app)
- [Haciendo una aplicación en Rails - Parte 2](/2020/04/15/stock-app-2)
- [Haciendo una aplicación en Rails - Parte 3](/2020/05/17/stock-app-3)

### Validaciones

En el estado actual de nuestra aplicacion, se puede almacenar cualquier dato el stock puede tener cantidades negativas, los campos de texto no tienen limites de longitud y otras cosas. Asi que debemos agregar validaciones de modelos, y para esto es exactamente que funcionan las pruebas unitarias asi que antes de iniciar primero nos aseguraremos que todo este bien ejecutando `rails t` y ejecutara todas las pruebas unitarias ubicadas en `\test`.

![test](/assets/images/posts/stock-app-4/test_sample.jpg){:.img-fluid}

Seguramente ya tengas algunas pruebas unitarias de controllers autogeneradas por Rails, si algunas de estas están fallando podes descartarlas ya que haremos nuestras propias pruebas.

Ahora iniciaremos el ciclo TDD y realizaremos las pruebas antes del codigo, las validaciones se aplican a nivel de modelo asi que iremos al archivo `\test\models\storage_test.rb` y tendremos las siguientes pruebas
{% highlight ruby linenos %}
require 'test_helper'

class StorageTest < ActiveSupport::TestCase
  test 'name and code are required' do
    storage = Storage.new({ name: nil, code: nil })
    refute storage.save, 'storage was saved'
    assert_not_nil storage.errors[:name]
    assert_not_nil storage.errors[:code]
  end

  test 'code maximum length is 4' do
    storage = Storage.new({ name: 'storage', code: '12345' })
    refute storage.save, 'storage was saved'
    assert_not_nil storage.errors[:code]
  end

  test "code can't be empty string" do
    storage = Storage.new({ name: 'storage', code: '' })
    refute storage.save, 'storage was saved'
    assert_not_nil storage.errors[:code]
  end
end
{% endhighlight %}

Los nombre de las pruebas deben ser directos para que cuando alguna falle, se sepa exactamente que es lo que va mal. Ahora detallare cada prueba

- La primer prueba intenta guardar un storage con name y code vacíos, con el método `refute` comprueba que el método `save` no guardo el storage (ya que este método devuelve un booleano), y despues con el método `assert_not_nil` comprobamos que se listan los errores para cada campo.
- La segunda prueba intenta guardar un code de 5 caracteres cuando queremos que el limite sea 4
- La tercera prueba intenta guardar un code vacío (no nil) y obviamente no debería guardarse

Si ejecutas `rails t` probablemente fallen asi que agreguemos estas validaciones con el método `validates` en nuestra clase `storage.rb`
{% highlight ruby linenos %}
class Storage < ApplicationRecord
  has_many :stocks, dependent: :destroy
  validates :name, presence: true
  validates :code, presence: true, length: { maximum: 4 }
end
{% endhighlight %}

Con este método le decimos a Rails que ejecute validaciones a la variable de acuerdo a los parámetros indicados, por ejemplo, el parámetro `presence: true` sirve para hacerlo requerido, luego con `length: { maximum: 4 }` le decimos que el campo no puede ser mas largo que 4 caracteres.
Con ese codigo, las pruebas deberian pasar, ahora vayamos a las pruebas para stock
{% highlight ruby linenos %}
require 'test_helper'

class StockTest < ActiveSupport::TestCase
  test "can't save stock with negative amount" do
    stock = Stock.new(storage_id: storages(:storage_one).id, product_id: products(:one).id, amount: -0.8)
    refute stock.save, 'stock is not valid with negative amount'
    assert_equal 'must be greater than or equal to 0', stock.errors[:amount].first
  end

  test 'zero amount is valid' do
    stock = Stock.new(storage_id: storages(:storage_two).id, product_id: products(:three).id, amount: 0)
    assert stock.save, 'stock with 0 is valid'
    assert stock.errors.empty?
  end

  test "can't save duplicated stock" do
    stock = Stock.new(storage_id: storages(:storage_two).id, product_id: products(:three).id, amount: 0)
    assert stock.save, 'new stock is not saved'
    duplicated_stock = Stock.new(storage_id: storages(:storage_two).id, product_id: products(:three).id, amount: 0)
    refute duplicated_stock.save, 'duplicated stock is saved'
  end

  test 'storage is required' do
    stock = Stock.new(storage_id: nil, product_id: products(:three).id, amount: 0)
    refute stock.save, 'stock is not valid without storage'
    assert_not_nil stock.errors[:storage_id]
  end

  test 'product is required' do
    stock = Stock.new(storage_id: storages(:storage_two).id, product_id: nil, amount: 0)
    refute stock.save, 'stock is not valid without product'
    assert_not_nil stock.errors[:product_id]
  end

  test 'amount is required' do
    stock = Stock.new(storage_id: storages(:storage_two).id, product_id: products(:three).id, amount: nil)
    refute stock.save, 'stock is not valid without amount'
    assert_not_nil stock.errors[:amount]
  end
end
{% endhighlight %}

Si te das cuenta, las ultimas tres pruebas son basicamente las mismas que vimos anteriormente asi que solo detallare las nuevas, aqui probablemente te llame la atención el siguiente codigo `storages(:storage_one).id` y esto esta haciendo uso de las `fixtures` que podes verlas como datos de prueba que pueden ser accedidos desde cualquier prueba, y tambien reflejan la base de datos de prueba, podes verificar los datos en la ruta `\test\fixtures`
- La primera prueba intenta guardar un stock con amount negativo y con `assert_equal` estamos verificando que el mensaje correcto sea incluido en los errores
- La segunda prueba guarda un stock amount en 0, lo cual puede ocurrir cuando se vacia el stock
- La tercer prueba intenta guardar el mismo stock dos veces

Ahora el codigo para pasar todas estas pruebas
{% highlight ruby linenos %}
class Stock < ApplicationRecord
  belongs_to :storage
  belongs_to :product
  self.primary_key = :storage_id, :product_id
  validates :product, uniqueness: { scope: :storage, message: "can't register twice on the same storage" }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end
{% endhighlight %}

Para validar que amount no sea negativo usamos el parámetro `numericality` y dentro le decimos que sea mayor o igual 0 con el parámetro `greater_than_or_equal_to`. Para validar que no se duplique el stock usamos el parámetro `uniqueness` y le indicamos cual es el alcance de la unicidad, en este caso tiene que ser entre product y storage

Podes ver otras validaciones disponibles en Rails en la [documentación oficial](https://guides.rubyonrails.org/active_record_validations.html)

##### Ejecucion en paralelo

Durante la realización de este post me encontre un problema técnico que puede ocurrirte, por defecto Rails ejecuta las pruebas unitarias en paralelo y esto puede llevar a un problema de concurrencia con la base de datos o archivos. Si esto tambien te sucede podes ir al archivo `test\test_helper.rb` y comentar la siguiente línea de codigo `parallelize(workers: :number_of_processors, with: :threads)` para solucionar el problema.

### Conclusión

Obviamente Rails provee muchos métodos para validar e incluso podemos hacer métodos extras para realizar validaciones mas complejas, y el hecho que podamos aplicar TDD sin mucha preparación previa es un punto a favor. En el siguiente post veremos como publicar nuestra aplicacion a la nube utilizando heroku.

Espero que haya sido de ayuda y comienza a usar validaciones!!
